PojisteniApp/Models/Pojistenec.cs
using System.ComponentModel.DataAnnotations;

namespace PojisteniApp.Models
{
    public class Pojistenec
    {
        
        public int  Id { get; set; }
        [Display(Name = "Jméno")]
        public string Name { get; set; }
        [Display(Name = "Příjmení")]
        public string LastName { get; set; }
        [Display(Name = "Adresa")]
        public string Adress { get; set; }
        [Display(Name = "Město")]
        public string City { get; set; }
        [Display(Name = "Email")]
        public string Email { get; set; }

        [Display(Name = "Telefon")]
        public string Phone { get; set; }
        [Display(Name = "PSČ")]
        public string PSC { get; set; }
        public List<Pojisteni>? Pojisteni { get; set; }

    }
}

PojisteniApp/Controllers/PojistenecController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PojisteniApp.Data;
using PojisteniApp.Models;

namespace PojisteniApp.Controllers
{
    public class PojistenecController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PojistenecController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pojistenec
        public async Task<IActionResult> Index()
        {
              return _context.Pojistenec != null ? 
                          View(await _context.Pojistenec.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Pojistenec'  is null.");
        }

        // GET: Pojistenec/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Pojistenec == null)
            {
                return NotFound();
            }

            var pojistenec = await _context.Pojistenec
                .FirstOrDefaultAsync(m => m.Id == id);

            //var details = (from d in _context.Conn
            //              where d.PojistenecId == id
            //              select d.PojisteniId).ToList();

            //var matchingPojisteni = (from p in _context.Pojisteni
            //                        where details.Contains(p.Id) 
            //                        select p).ToList();

            var matchingPojisteni = await (from d in _context.Conn
                                     join p in _context.Pojisteni on d.PojisteniId equals p.Id
                                     where d.PojistenecId == id
                                     select p).ToListAsync();

            PojisteniDetails pojisteniDetails = new PojisteniDetails();
            pojisteniDetails.Pojisteni = matchingPojisteni;
            pojisteniDetails.Pojistenec = pojistenec;

            if (pojistenec == null)
            {
                return NotFound();
            }

            return View(pojisteniDetails);
        }

        // GET: Pojistenec/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pojistenec/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,LastName,Adress,City,Email,Phone,PSC")] Pojistenec pojistenec)
        {
            if (ModelState.IsValid)
            {
                _context.Add(pojistenec);
                await _context.SaveChangesAsync();

            }
            Conn conn = new Conn();
            var pojistenecId = pojistenec.Id;
            conn.PojistenecId = pojistenecId;
            conn.PojisteniId = null;


            if (ModelState.IsValid)
            {
                _context.Add(conn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(pojistenec);
        }

        // GET: Pojistenec/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Pojistenec == null)
            {
                return NotFound();
            }

            var pojistenec = await _context.Pojistenec.FindAsync(id);
            if (pojistenec == null)
            {
                return NotFound();
            }
            return View(pojistenec);
        }

        // POST: Pojistenec/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,LastName,Adress,City,Email,Phone,PSC")] Pojistenec pojistenec)
        {
            if (id != pojistenec.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pojistenec);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PojistenecExists(pojistenec.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(pojistenec);
        }

        // GET: Pojistenec/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Pojistenec == null)
            {
                return NotFound();
            }

            var pojistenec = await _context.Pojistenec
                .FirstOrDefaultAsync(m => m.Id == id);
         
            if (pojistenec == null)
            {
                return NotFound();
            }

            return View(pojistenec);
        }

        // POST: Pojistenec/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Pojistenec == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pojistenec'  is null.");
            }
            var pojistenec = await _context.Pojistenec.FindAsync(id);
            var conn = _context.Conn.SingleOrDefault(x => x.PojistenecId == id);


            if (pojistenec != null)
            {
                _context.Pojistenec.Remove(pojistenec);
                _context.Conn.Remove(conn);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PojistenecExists(int id)
        {
          return (_context.Pojistenec?.Any(e => e.Id == id)).GetValueOrDefault();
        }




        // GET: Conn/Create
        public IActionResult CreateNewPojisteni(int? id)
        {
          
          
            ViewData["PojisteniId"] = new SelectList(_context.Pojisteni, "Id", "Type");

            return View();
        }

        // POST: Conn/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateNewPojisteni([Bind("PojistenecId,PojisteniId")] Conn conn, int id)
        {

            conn.PojistenecId = id;
            ViewData["PojisteniId"] = new SelectList(_context.Pojisteni, "Id", "Type", conn.PojisteniId);

            if (!ModelState.IsValid)
            {
                _context.Add(conn);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(conn);
        }





        // GET: Conn/Delete/pridano mnou
        public async Task<IActionResult> DeletePojisteni(int? PojistenecId, int? PojisteniId)
        {
            if (PojistenecId == null || _context.Conn == null || PojisteniId == null) 
            {
                return NotFound();
            }


            var pojistenec = await _context.Pojistenec
                .FirstOrDefaultAsync(m => m.Id == PojistenecId);

            var pojisteni = await _context.Pojisteni
                .FirstOrDefaultAsync(m => m.Id == PojisteniId);

            PojisteniDetails pojisteniDetails = new PojisteniDetails();
            pojisteniDetails.Route = pojisteni;
            pojisteniDetails.Pojistenec = pojistenec;


        


            if (pojistenec == null || pojisteni == null)
            {
                return NotFound();
            }
     
            return View(pojisteniDetails);
        }


        // POST: Pojisteni/Delete/pridano mnou
        [HttpPost, ActionName("DeletePojisteniConfirmed")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeletePojisteniConfirmed(int? PojistenecId, int? PojisteniId)
        {
            if (_context.Conn == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Pojisteni'  is null.");
            }

            var conn = await _context.Conn
            .Where(row => row.PojisteniId == PojisteniId &&
                           row.PojistenecId == PojistenecId)
            .FirstOrDefaultAsync();



            if (conn != null)
            {
                _context.Conn.Remove(conn);

  
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }








        // GET: Pojisteni/Details/5
        public async Task<IActionResult> DetailPojisteni(int? id)
        {
            if (id == null || _context.Pojisteni == null)
            {
                return NotFound();
            }

            var pojisteni = await _context.Pojisteni
                .FirstOrDefaultAsync(m => m.Id == id);
            if (pojisteni == null)
            {
                return NotFound();
            }
            PojisteniDetails pojisteniDetail = new PojisteniDetails();
            pojisteniDetail.Route = pojisteni;
            return View(pojisteniDetail);
        }

    }
}

PojisteniApp/Views/Pojistenec/Create.cshtml
@model PojisteniApp.Models.Pojistenec

@{
    ViewData["Title"] = "Create";
}
<h4 class="text-center">Vytvořit pojištence</h4>
<hr />


    <div class="row ">
        <div class="col">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row justify-content-center ">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="Name" class="control-label"></label>
                            <input asp-for="Name" class="form-control" />
                            <span asp-validation-for="Name" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4 ">
                        <div class="form-group">
                            <label asp-for="LastName" class="control-label"></label>
                            <input asp-for="LastName" class="form-control" />
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="Adress" class="control-label"></label>
                            <input asp-for="Adress" class="form-control" />
                            <span asp-validation-for="Adress" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="City" class="control-label"></label>
                            <input asp-for="City" class="form-control" />
                            <span asp-validation-for="City" class="text-danger"></span>
                        </div>
                    </div>
                </div>

            <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="Email" class="control-label"></label>
                            <input asp-for="Email" class="form-control" />
                            <span asp-validation-for="Email" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="Phone" class="control-label"></label>
                            <input asp-for="Phone" class="form-control" />
                            <span asp-validation-for="Phone" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            <div class="row justify-content-center">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label asp-for="PSC" class="control-label"></label>
                            <input asp-for="PSC" class="form-control" />
                            <span asp-validation-for="PSC" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-4"></div>
                </div>
                <div class="form-group text-center m-4">
                    <input type="submit" value="Vytvořit" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Zpět na seznam</a>
    </div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PojisteniApp/Views/Pojistenec/CreateNewPojisteni.cshtml
@model PojisteniApp.Models.Conn

@{
    ViewData["Title"] = "Create";
}



<h4>Zadejte pojištení, které chcete připojit k pojištěnci</h4>
<hr />
<div class="row justify-content-center">
    <div class="col-md-4 ">
        <form asp-action="CreateNewPojisteni">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
           
            <div class="form-group ">
                <label asp-for="PojisteniId" class="control-label"></label>
                <select asp-for="PojisteniId" class="form-control" asp-items="ViewBag.PojisteniId"></select>
            </div>

            <div class="form-group m-4 text-center">
                <input type="submit" value="Vytvořit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Zpět na seznam</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

PojisteniApp/Views/Pojistenec/Delete.cshtml
@model PojisteniApp.Models.Pojistenec

@{
    ViewData["Title"] = "Delete";
}




<div>
    <h4>Smazat pojištěnce @Html.DisplayFor(model => model.Name)  @Html.DisplayFor(model => model.LastName)</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.PSC)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.PSC)
        </dd>
    </dl>
    <div class="text-center">
        <form asp-action="Delete">
            <input type="hidden" asp-for="Id" />
            <input type="submit" value="Smaž" class="btn btn-danger" />

        </form>
    </div>
    <p>
        <a asp-action="Index">Zpět na seznam</a>
    </p>
    
</div>

PojisteniApp/Views/Pojistenec/DeletePojisteni.cshtml
@model PojisteniApp.Models.PojisteniDetails

@{
    ViewData["Title"] = "Delete";
}

<div>
    <h4>Smazat pojištěnce </h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Route.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Route.Type)
        </dd>
  
    </dl>
    <div class="text-center">
        <form asp-controller="Pojistenec" asp-action="DeletePojisteniConfirmed" asp-route-PojistenecId="@Model?.Pojistenec?.Id" asp-route-PojisteniId="@Model?.Route?.Id">
            <input type="hidden"/>
            <input type="submit" value="Smaž" class="btn btn-danger" />

        </form>
    </div>
    <p>
        <a asp-action="Index">Zpět na seznam</a>
    </p>

</div>

PojisteniApp/Views/Pojistenec/DetailPojisteni.cshtml
@model PojisteniApp.Models.PojisteniDetails

@{
    ViewData["Title"] = "Details";
}


<div>
    <h4>Detail pojištění pro @Html.DisplayFor(model => model.Route.Type)</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Route.Type)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Route.Type)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Route.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Route.Price)
        </dd>
    </dl>
</div>


@*<div>
    <a asp-action="Details" asp-route-id="@Model?.Pojistenec?.Id" class="btn btn-primary">Detaily</a>
</div>
*@

PojisteniApp/Views/Pojistenec/Details.cshtml
@model PojisteniApp.Models.PojisteniDetails

@{
    ViewData["Title"] = "Details";
}

<div>
    <h4>Pojistenec @Html.DisplayFor(model => model.Pojistenec.Name) @Html.DisplayFor(model => model.Pojistenec.LastName) </h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.Adress)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.Adress)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.City)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.City)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Pojistenec.PSC)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Pojistenec.PSC)
        </dd>

      
        @if (Model.Pojisteni != null && Model.Pojisteni.Count > 0)
        {

            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                       
                        <th scope="col">Pojištění</th>
                        <th scope="col">Částka</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var pojisteni in Model.Pojisteni)
                    {
                        <tr>
                            <td>@pojisteni.Type</td>
                            <td>@pojisteni.Price</td>
                            <td>
                                <div class="row justify-content-start">
                                    <div class="col-3 m-1">

                                        <form asp-action="DeletePojisteni" asp-route-PojistenecId="@Model?.Pojistenec.Id" asp-route-PojisteniId ="@pojisteni.Id">
                                            <input type="hidden">
                                            <input type="submit" value="Smaž" class="btn btn-danger btn-sm" />
                                        </form>

                                    </div>
                                 <div class="col-3 m-1">
                                        <a asp-action="DetailPojisteni" asp-route-id="@pojisteni.Id" class="btn btn-primary btn-sm">Detail pojištění</a>
                                    </div>
                                </div>
                            </td>
 
                        </tr>
                    }
                </tbody>
            </table>
        }
        else
        {
            <p>No insurance found.</p>
        }
    </dl>

    <div class="text-center">
        <a asp-action="CreateNewPojisteni" asp-route-id="@Model?.Pojistenec?.Id" class="btn btn-primary">Vytvořit nové pojištění</a>
    </div>


</div>

  


<p>
    <a asp-action="Index">Zpět na seznam</a>
</p>

PojisteniApp/Views/Pojistenec/Edit.cshtml
@model PojisteniApp.Models.Pojistenec

@{
    ViewData["Title"] = "Edit";
}


<h4>Upravit pojištěnce  @Html.DisplayFor(model => model.Name) @Html.DisplayFor(model => model.LastName) </h4>
<hr />
<div class="row">
    <div class="col">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="LastName" class="control-label"></label>
                        <input asp-for="LastName" class="form-control" />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                </div>
         

            </div>
       

            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Adress" class="control-label"></label>
                        <input asp-for="Adress" class="form-control" />
                        <span asp-validation-for="Adress" class="text-danger"></span>
                    </div>
                </div>
             
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="City" class="control-label"></label>
                        <input asp-for="City" class="form-control" />
                        <span asp-validation-for="City" class="text-danger"></span>
                    </div>
                </div>
             
            </div>
     


            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Email" class="control-label"></label>
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
             
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="Phone" class="control-label"></label>
                        <input asp-for="Phone" class="form-control" />
                        <span asp-validation-for="Phone" class="text-danger"></span>
                    </div>
                </div>
            
            </div>
      


            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <label asp-for="PSC" class="control-label"></label>
                        <input asp-for="PSC" class="form-control" />
                        <span asp-validation-for="PSC" class="text-danger"></span>
                    </div>
                </div>
             
            </div>
      

            <div class="form-group text-center m-4">
                <input type="submit" value="Uložit" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


<div>
    <a asp-action="Index">Zpět na seznam</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

PojisteniApp/Views/Pojistenec/Index.cshtml
@model IEnumerable<PojisteniApp.Models.Pojistenec>

@{
    ViewData["Title"] = "Index";
}


<div class="text-center">
    <p>
        <a asp-action="Create" class="btn btn-primary">Vytvořit nového pojištěnce</a>
    </p>

</div>

<div class="container-fluid">
    <div class="row">

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Adress)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Adress)
                        </td>
                        <td>
                             <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary">Detaily</a>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">Upravit</a> 
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Smazat</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>

   

</div>